stages:
  initime:
    vars:
      - container:
          out: /mnt/out
          tmf: /mnt/in/TRACMASS_run.hdf5
      - ../../params.yaml
    cmd:
      singularity run --no-home --cleanenv --containall
        --bind $(realpath $(dvc root)/../..)/${data.hdf5}:${container.out}:rw
        --bind $(realpath $(dvc root)/../..)/${data.tracmass_hdf5}:${container.tmf}:ro
      ../../src/dians-${package_version}.sif create_column
        --tracmass-hdf5=${container.tmf}
        --column-dst=${container.out}
        --column=initime
    deps:
      - ../../${data.tracmass_hdf5}
      - ../../src/dians-${package_version}.sif
    outs:
      - ../../${data.initime}
